### ISSUE TITLE
[BUG]: "Cannot read property 'version' of undefined" when running reset

### ISSUE THREAD

**Issue by rjmackay** [sensedeep/onetable-cli#14]
**Describe the bug**
When running `reset` onetable-cli fails with the error "TypeError: Cannot read property 'version' of undefined"

**To Reproduce**
Run `onetable --profile dev --debug reset`, while running migrations locally not from a lambda.

```
TypeError: Cannot read property 'version' of undefined
    at CLI.move (file:///Users/robbie/devel/veho/janus/node_modules/onetable-cli/dist/cli.js:313:45)
```

I think this is related to https://github.com/sensedeep/onetable-cli/blob/main/src/cli.js#L321
This expects a return value, but as far as I can see Migrate doesn't actually return a value. This might be a discrepancy between the lambda and running locally?

**Expected behavior**
Migration should run without error

**Environment (please complete the following information):**
 - OS: OSX 11.6
 - Node Version: 14.18.1

**Additional context**

Migrate.json:
```json
{
  "onetable": {
    "name": "janus",
    "isoDates": true,
    "region": "us-east-1",
    "schema": {
      "version": "0.0.1",
      "indexes": {
        "primary": {
          "hash": "pk",
          "sort": "sk"
        }
      },
      "models": {
        "_Migration": {
          "pk": { "type": "String" },
          "sk": { "type": "String" },
          "date": { "type": "Date" },
          "description": { "type": "String" },
          "path": { "type": "String" },
          "version": { "type": "String" }
        }
      }
    }
  },
  "dir": "migrations/",
  "profiles": {
    "local": {
      "region": "localhost",
      "endpoint": "http://localhost:4567"
    },
    "dev": {
      "region": "us-east-1"
    }
  }
}
```

**Comment by mobsense** [comment]
Should be fixed now.
