### ISSUE TITLE
Migration failed Cannot use import statement outside a module

### ISSUE THREAD

**Issue by RyanHow** [sensedeep/onetable-cli#15]
**Describe the bug**
 
 
```
onetable-migrate/latest.js:1
import schema from "./schemas/schema.0.0.1";
^^^^^^
```

 `Migration failed Cannot use import statement outside a module`

Command
`npx onetable-cli --dir onetable-migrate reset`
 
contents of onetable-migrate
```
0.0.1.js  0.0.2.js  0.0.3.js  index.js  latest.js  migrate.json  schemas

./schemas:
schema.0.0.1.js  schema.0.0.2.js  schema.0.0.3.js
```

latest.js
```
import schema from "./schemas/schema.0.0.1";
export default {
  version: "latest",
  description: "Database reset to latest version",
  schema,
  async up(db, migrate, params) {
    const table = await db.describeTable();
    console.log(table);
  },
  async down(db, migrate, params) {
  }
};
```

Ubuntu Linux
Node v14.17.0
NPM v7.19.1
 
**Additional context**
It seems that it isn't interpreting the schema as es modules??

Anything else I can try?

**Comment by mobsense** [comment]
Add a package.json in the directory and set type: "module".  Or use require.

**Comment by RyanHow** [comment]
Thanks. That worked. I ended up restructuring the project a little bit because other JS in the directory didn't work with modules enabled. So migrations and CLI are all in a self-contained folder.

I also tried `.mjs` extensions, but that didn't work.

**Comment by mobsense** [comment]
Fixed by having a package.json in the migrations directory.
