### ISSUE TITLE
[BUG]: Installing issue

### ISSUE THREAD

**Issue by enstulen** [sensedeep/onetable-cli#16]
**Describe the bug**
Error when installing from yarn and npm.

**To Reproduce**
1. Run `yarn add onetable-cli` (Doesn't work with `npm i onetable-cli -g` either)

**Expected behavior**
Installing the package

**Screenshots**

Running `yarn add onetable-cli`
![Skjermbilde 2022-06-20 kl  16 28 53](https://user-images.githubusercontent.com/7783861/174624130-091d8ada-52bf-4430-8f39-ac4866a07143.png)

Running `npm i onetable-cli -g`

![Skjermbilde 2022-06-20 kl  16 29 08](https://user-images.githubusercontent.com/7783861/174624161-e75f9897-7e43-4166-9ab5-2fa4b7458be2.png)

**Environment (please complete the following information):**
 - OS: MacOS
 - Node Version: v14.18.1

**Comment by mobsense** [comment]
What version npm. You need npm version 7.

**Comment by enstulen** [comment]
I was using npm version 6, but it doesn't work with version 7 or 8 either. 

With `npm i onetable-cli -g` I get: 

```
npm ERR! Cannot set property 'dev' of null
```

 I'm using `yarn` with version `1.22.19` in the project. 

I'm using [Volta](https://docs.volta.sh/guide/) to pin the node, yarn and npm versions

**Comment by mobsense** [comment]
that looks like a volta issue.

Can you test on a system without volta?

**Comment by mpontus** [comment]
I also couldn't install `onetable-cli` because of dependency on `js-clone` library which is no longer listed on NPM.

![image](https://github.com/user-attachments/assets/501b42f6-144c-4a26-8975-651e2ac8fef3)

**Comment by mobsense** [comment]
The js-clone is an internal package. Strange issue, deep down in NPM it cannot handle this on some systems only.

We've pushed a new version and removed the internal packages and made them pure source references and not dependencies.

**Comment by mpontus** [comment]
@mobsense The package can now be installed using yarn, how I'm having trouble running it after installation. It's also failing when ran via `npx` with the same error.

![image](https://github.com/user-attachments/assets/759407d1-e8d1-47ed-9820-9c5737a1f3f8)

**Comment by mobsense** [comment]
Thanks for reporting, please try again and let us know.

**Comment by mpontus** [comment]
@mobsense It worked! Thanks for a timely fix :)
