### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by mervinyan** [sensedeep/onetable-cli#17]
**Describe the bug**
Got `ERR_MODULE_NOT_FOUND` error when running any onetable command after installing `onetable-cli` globally

**To Reproduce**
1. Enter command `npx onetable-cli --version` in terminal
2. Got Error [ERR_MODULE_NOT_FOUND]
![2022-08-08_10-13](https://user-images.githubusercontent.com/1260845/183439014-631edadc-f1fe-4f69-81e2-6787c17a5c72.png)

3. Got the same error after installing `onetable-cli` globally via command command `npm install -g onetable-cli` 
4. Checked the source code saw it references `onetable` folder however it doesn't exsit
![image](https://user-images.githubusercontent.com/1260845/183441153-1926d1fb-6dc1-44b2-9b6e-8e0fe1065c35.png)

**Expected behavior**
onetable command run successfully 

**Screenshots**
![2022-08-08_10-13](https://user-images.githubusercontent.com/1260845/183439014-631edadc-f1fe-4f69-81e2-6787c17a5c72.png)

**Environment (please complete the following information):**
 - OS
 Ubuntu 22.04
 - Node Version
 Node: V16.16.0
 NPM: V7.18.1

**Additional context**

**Comment by mobsense** [comment]
Thank you. Should be fixed now.
