### ISSUE TITLE
Update to aws-sdk v3

### ISSUE THREAD

**Issue by tagleeson** [sensedeep/onetable-cli#18]
aws-sdk v2 is deprecated

**Comment by mobsense** [comment]
We support V3 already.

V2 is still supported as some users are still actively using V2.

**Comment by tagleeson** [comment]
I'm not sure what you mean that v3 is supported already. Could you explain how one would configure this project to use aws sdk v3?

**Comment by mobsense** [comment]
Sorry for the misunderstanding. I thought you were referring to OneTable (dynamodb-onetable) and not the cli.

Yes, the CLI is currently V2.

We are planning upgrading all to V3 over the next quarter.

**Comment by tagleeson** [comment]
Thanks for the update
