### ISSUE TITLE
[BUG]: the 'all' command does not respect migration failures

### ISSUE THREAD

**Issue by jousby** [sensedeep/onetable-cli#19]
**Describe the bug**
I'm running the command `onetable --force all` as a pre deploy step in my CICD pipeline. This way if a new migration script turns up in my migrations folder it gets applied automatically and then the associated code that uses this new schema gets deployed in a subsequent pipeline step. 

If i make a mistake in a migration script this step fails and stops the pipeline run, subsequently stopping the the associated code/commit getting deployed (nice). The result of a failed migration is that i end up with a row in the table for that migration (under the _Migration entity/type) for that version with a status equal to the error message (as opposed to status=success). 

My problem starts on the next subsequent run of a pipeline. The migration step that runs `onetable --force all` happily passes as it thinks the schema migration that failed in the previous run was successfully applied because there is a row for it in the table (even though it has a status that is not 'success').

**Expected behavior**
The `all` command should always return a non zero exit code if the most recent migration is not a success.
The `all` command should not attempt to apply new migrations if there is a migration version in the chain that is not successful.

Interesting question around should it try to reapply a failed migration on every run? i.e lets say you have a file 2.0.0.js that failed the first run and you check in an update that fixed the reason it failed. Should the `all` command automatically try to reapply 2.0.0.js on every run if it saw 2.0.0.js fail in the previous run. My vote would be for yes it should. If a migration fails then it would be up to the user to get the table back to state where the 2.0.0.js migration will be successful, before checking in the updated 2.0.0.js that will trigger a new run. Or make it optional behind a switch `--retryFailed=true`.

**Environment (please complete the following information):**
 - OS (ubuntu)
 - Node Version: v20.14
 - OneTable CLI: v1.3.1

**Comment by mobsense** [comment]
Thank you for the issue. Let us dig into that and get back to you.

**Comment by mobsense** [comment]
Thinking about this....

Some folks may create new migrations and step over past failed migrations. i.e. if 0.0.2 failed, then create a 0.0.3 that fixes the problem.

So we probably can't change the behavior without a switch as you suggest. I like retryFailed switch idea. I presume we should just retry the last failed migration and not prior failures?  Or do you think it should be all the last failing migrations?

**Comment by mobsense** [comment]
For background, the way we use it with the SenseDeep migration controller. We fix a failed migration and use the "repeat" command to retry the failed migration.

**Comment by mobsense** [comment]
Okay, got a fix for this.

Added --retry-failed.

This will retry the most recent consecutive sequence of failed migrations using a "repeat" action. 

This requires a fix applied to the migrate repo.

Please let me know if these patches fix your issue and we'll test locally and then release.

**Comment by jousby** [comment]
Nice. That behavior for the --retry-failed flag sounds like it will work for our usecase thanks.
