### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by bytekast** [sensedeep/onetable-cli#2]
Installation results in:

```
npm ERR! Could not install from "../../../../../usr/local/lib/node_modules/onetable-cli/src/paks/js-blend" as it does not contain a package.json file.
```

**Comment by mobsense** [comment]
Can you please give a few more details as that works here.

Can you give your npm version, node version and the exact command. Not sure whey you are seeing ../../../..

Can you try 

    npm i onetable-cli -g

Thanks

**Comment by bytekast** [comment]
That's what I did.

`npm i onetable-cli -g`
npm 6.14.11
node v14.16.0

**Comment by mobsense** [comment]
I'll try on more systems here. I'm using npm 7.6.0 and node v15.11.0 versions.

Try an install locally. You should then see that module as:

./node_modules/onetable-cli/src/paks/js-blend

**Comment by bytekast** [comment]
node 14.x is the latest supported version in lambda so I'm sticking with that.

I'll try a local install. thanks

**Comment by mobsense** [comment]
I can replicate with an old version of npm.  Will track down a solution.

Thanks for reporting.

**Comment by mobsense** [comment]
Can you try with an updated npm to the current supported version: v7.7.6.

That seemed to fix it for me.

**Comment by bytekast** [comment]
awesome, it worked! thanks

**Comment by mobsense** [comment]
NPM added support for local dependencies in the current version.

Thank you for your time in reporting these issues. Really helpful!!

```
    "dependencies": {
        "js-blend": "./src/paks/js-blend",
        "js-clone": "./src/paks/js-clone",
        "js-combine": "./src/paks/js-combine",
        "js-dates": "./src/paks/js-dates",
        "js-file": "./src/paks/js-file",
        "js-log": "./src/paks/js-log",
    },
```
