### ISSUE TITLE
[DOCS]: Add documentation for configuring profiles

### ISSUE THREAD

**Issue by rjmackay** [sensedeep/onetable-cli#5]
**Describe the bug**
There is no documentation for how to configure profiles.

**Additional context**
Docs tell you how to pick a profile, but provide no context to what that does. From reading the code it looks like maybe you can set `profiles` in `migrate.json` but I'm not sure how best to use that?

**Comment by mobsense** [comment]
Sure, thank you. We'll add.

Profiles are pretty simple. When loading, the map for a profile is hoisted to the top level. Here is one migrate.json we use:

If the profile is set to 'dev', the [dir, name, endpoint] properties are copied to the root level.

```
{
    config: ['../pak.json', '../product.json', '../CONFIG/service-keys.json'],
    profiles: {
        dev: {
            dir: './migrations',
            name: 'sensedb',
            endpoint: 'http://localhost:8000'
        },
        qa: {
            name: 'sensedb',
            arn: 'arn:aws:lambda:us-east-1:xxxx:function:migrate-qa-invoke'
        },
        prod: {
            name: 'sensedb',
            arn: 'arn:aws:lambda:us-east-1:xxxx:function:migrate-prod-invoke'
        }
    }
}

```

**Comment by rjmackay** [comment]
Awesome. Thank you!

**Comment by mobsense** [comment]
Let me know how you go with migrations in general. We find them vital to our workflow. Just setup discussion on this repo for this purpose.
