### ISSUE TITLE
[BUG]: AWS params ignored when endpoint is set

### ISSUE THREAD

**Issue by rjmackay** [sensedeep/onetable-cli#8]
**Describe the bug**
onetable-cli ignores other AWS config if endpoint is set

**To Reproduce**
1. Set up a migrate.json like this
```{
  "schema": "src/data/db/schema.ts",
  "name": "mytable",
  "profiles": {
    "local": {
      "aws": {
        "endpoint": "http://localhost:4567",
        "region": "local",
        "accessKeyId": "test",
        "secretAccessKey": "test"
      }
    }
  }
}

```
2. Create the table in dynamodb-local with the same creds above
3. Run any onetable-cli commands

```
Cannot communicate with DynamoDB "mytable" at "localhost"
Cannot do operations on a non-existent table
```

**Expected behavior**
Onetable-cli should honor the other aws properties when using a local endpoint.

**Additional context**
When running dynamodb-local without -sharedDb it creates a separate table for each region/accesskey, so if we don't pass the params through then it can't find the db table.

**Comment by mobsense** [comment]
Is it the keys or the region too?  We typically just set the local region to 'localhost'.

**Comment by mobsense** [comment]
Sorry this got overlooked.

Actually, looks like it is fixed now. I'll close. Let me know if it doesn't work for you, but works here now.
